#!/bin/bash

set -xe

ROOT=`pwd`
KMS_CMAKE_UTILS_DIR=$ROOT/kms-cmake-utils
KMS_JSONRPC_DIR=$ROOT/kms-jsonrpc
KMS_JSONCPP_DIR=$ROOT/jsoncpp


#Build jsoncpp
./build-kms-jsoncpp.sh

LIBRARY_PATH="$KMS_JSONCPP_DIR/src/lib_json";
CMAKE_MODULE_PATH="$KMS_CMAKE_UTILS_DIR;$KMS_CMAKE_UTILS_DIR/CMake";
PKG_CONFIG_PATH="$KMS_JSONCPP_DIR/pkg-config/";
CMAKE_CXX_FLAGS=" -I$KMS_JSONCPP_DIR/include"
cd $KMS_JSONRPC_DIR;
env PKG_CONFIG_PATH=$PKG_CONFIG_PATH cmake -DCMAKE_MODULE_PATH=$CMAKE_MODULE_PATH -DCMAKE_CXX_FLAGS="$CMAKE_CXX_FLAGS"
env LIBRARY_PATH=$LIBRARY_PATH make

cd $ROOT
